services:
  - type: web
    name: milind-kashyap-portfolio
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.x.0
      - key: npm_config_legacy_peer_deps
        value: "true"
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

